/**
 * Generates MP3 files under public/audio and refreshes lib/generated/audio-manifest.ts.
 *
 * Usage (from repo root):
 *   AZURE_SPEECH_KEY=... AZURE_SPEECH_REGION=westeurope npx tsx --tsconfig tsconfig.json scripts/generate-lesson-audio.mts
 *   npx tsx --tsconfig tsconfig.json scripts/generate-lesson-audio.mts --silence-ffmpeg
 *   npx tsx --tsconfig tsconfig.json scripts/generate-lesson-audio.mts --macos-say
 *
 * Flags: --force (overwrite), --silence-ffmpeg (short silent MP3 via ffmpeg; no API key),
 *        --macos-say (Lithuanian MP3 via the local macOS Ona voice; no API key).
 */

import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import audioPaths from "../lib/lesson-audio-paths.ts";
import lessonsMod from "../lib/lessons/index.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

async function azureTts(text: string, region: string, key: string): Promise<Buffer> {
  const url = `https://${region}.tts.speech.microsoft.com/cognitiveservices/v1`;
  const ssml = `<speak version='1.0' xml:lang='lt-LT'><voice xml:lang='lt-LT' name='lt-LT-OnaNeural'>${escapeXml(
    text,
  )}</voice></speak>`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Ocp-Apim-Subscription-Key": key,
      "Content-Type": "application/ssml+xml",
      "X-Microsoft-OutputFormat": "audio-16khz-128kbitrate-mono-mp3",
      "User-Agent": "lt-book-audio-generator",
    },
    body: ssml,
  });
  if (!res.ok) {
    throw new Error(`Azure TTS ${res.status}: ${await res.text()}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

function ffmpegSilence(outPath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const p = spawn(
      "ffmpeg",
      [
        "-y",
        "-f",
        "lavfi",
        "-i",
        "anullsrc=r=24000:cl=mono",
        "-t",
        "0.2",
        "-q:a",
        "9",
        "-acodec",
        "libmp3lame",
        outPath,
      ],
      { stdio: "ignore" },
    );
    p.on("error", reject);
    p.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited ${code}`));
    });
  });
}

function runCommand(cmd: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { stdio: "ignore" });
    p.on("error", reject);
    p.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} exited ${code}`));
    });
  });
}

async function macosSayMp3(text: string, outPath: string): Promise<void> {
  const tmpAiff = `${outPath}.${process.pid}.aiff`;
  try {
    await runCommand("say", ["-v", "Ona", "-o", tmpAiff, text]);
    await runCommand("ffmpeg", [
      "-y",
      "-v",
      "error",
      "-i",
      tmpAiff,
      "-codec:a",
      "libmp3lame",
      "-q:a",
      "4",
      outPath,
    ]);
  } finally {
    await fs.rm(tmpAiff, { force: true });
  }
}

async function writeManifest(urls: Set<string>): Promise<void> {
  const ordered = [...urls].sort();
  const lines = ordered.map((u) => `  ${JSON.stringify(u)},`).join("\n");
  const body = `/**
 * Auto-generated by scripts/generate-lesson-audio.mts — do not edit by hand.
 */
export const AUDIO_MANIFEST: ReadonlySet<string> = new Set<string>([\n${lines}\n]);
`;
  const manifestPath = path.join(root, "lib/generated/audio-manifest.ts");
  await fs.writeFile(manifestPath, body, "utf8");
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const force = process.argv.includes("--force");
  const silence = process.argv.includes("--silence-ffmpeg");
  const macosSay = process.argv.includes("--macos-say");
  const key = process.env.AZURE_SPEECH_KEY;
  const region = process.env.AZURE_SPEECH_REGION ?? "";

  if (!silence && !macosSay && (!key || !region)) {
    console.error(
      "Set AZURE_SPEECH_KEY and AZURE_SPEECH_REGION, or pass --macos-say (macOS Ona + ffmpeg) or --silence-ffmpeg.",
    );
    process.exit(1);
  }

  const jobs = audioPaths.collectAllLessonsAudioJobs(lessonsMod.LESSONS);
  const manifest = new Set<string>();

  console.log(`Jobs: ${jobs.length}`);

  for (const job of jobs) {
    const abs = path.join(root, job.fsPath);
    if (!force && (await fileExists(abs))) {
      manifest.add(job.url);
      continue;
    }

    await fs.mkdir(path.dirname(abs), { recursive: true });

    if (key && region) {
      const buf = await azureTts(job.text, region, key);
      await fs.writeFile(abs, buf);
    } else if (macosSay) {
      await macosSayMp3(job.text, abs);
    } else if (silence) {
      await ffmpegSilence(abs);
    }

    manifest.add(job.url);
    console.log("wrote", job.url);
  }

  await writeManifest(manifest);
  console.log(`Manifest: ${manifest.size} URLs`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
